M48
; DRILL file {KiCad 7.0.5} date Sat Jul 15 11:17:08 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-07-15T11:17:08-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X4.4522Y-3.3776
X4.6431Y-3.3776
T2
X4.4404Y-3.2583
X4.6549Y-3.2583
T0
M30
