M48
; DRILL file {KiCad 7.0.5} date Mon Jul 10 21:20:45 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-07-10T21:20:45-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X4.5683Y-2.3359
X4.7593Y-2.3359
T2
X4.5565Y-2.2166
X4.7711Y-2.2166
T0
M30
