M48
; DRILL file {KiCad 7.0.5} date Fri Jul 28 19:51:42 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-07-28T19:51:42-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X4.4598Y-5.0645
X4.6508Y-5.0645
T2
X4.448Y-5.1838
X4.6626Y-5.1838
T0
M30
